export { Avatar } from './avatar/avatar.component'
export { PageTitle } from './page-title/page-title.component'
export { Heading } from './heading/heading.component'
export { ErrorHelper } from './error-helper/error-helper.component'
export { ConfirmedDiagnosisLabel } from './confirmed-diagnosis-label/confirmed-diagnosis-label.component'
export { Divider } from './divider/divider.component'
