export { DocumentLayout } from './document/document.layout'
export { Flex } from './flex/flex.layout'
export { Drawer } from './drawer/drawer.layout'
export { DropMenu } from './drop-menu/drop-menu.component'
export { StaticLogo } from './static-logo/static-logo.layout'
export { Form } from './form/form.layout'
