export { DashboardIcon } from './dashboard.icon'
export { CalendarIcon } from './calendar.icon'
export { PeopleIcon } from './people.icon'
export { DoctorsIcon } from './doctors.icons'
export { MessageIcon } from './message.icon'
export { StarIcon } from './star.icon'
export { FinancesIcon } from './finances.icon'
